# start with current version
version: '3.6'

# docker-compose build
# docker-compose run
# docker-compose up (both in 1 step)
# docker-compose down (removes older references)

# forces updating for nodemon and server refersh of container
# volumes:
#  - ./:/usr/src/smart-brain-api  

services:

  # BACKEND
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api  

  # DB
  postgres:
    container_name: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
    build: ./postgres    
    ports:
      - "5432:5432"
